/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CommandPattern.*;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author PALA
 */
public class VistaJugador extends javax.swing.JFrame {
    private CommandManager commandManager; // Esto es un singleton, deberia de colocarse en el servidor o en un cliente, la verdad ahi esa logica no me la se
    private JButton[][] dmgMatrix;

    /**
     * Creates new form VistaJugador
     */
    public VistaJugador() {
        initComponents();
        initializerMatrix(pnlMostrarDmgHabilidades,dmgMatrix);
        // inicializamos el CommandManager
        commandManager = CommandManager.getInstance();
        commandManager.reigsterCommand(new CardCommand());
        commandManager.reigsterCommand(new ImageCommand());
        
        // listener para detectar el enter
        txtConsola.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent e){
                // detectamos el "enter"
                if(e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
                    e.consume(); // prevencion para el salto de linea
                    processCommand();
                }
            }
        
        });
    }
    
    // ---------- METODOS VARIOS ----------//
    
    private void processCommand(){
        String input = getLastCommand();
        if(input.isEmpty()) return;
        
        String[] tokens = CommandUtil.tokenizeArgs(input);
        
        if(tokens.length>0){
            String commandName = tokens[0];
            String[] args = new String[tokens.length -1];
            System.arraycopy(tokens, 1, args, 0, args.length);
            
            iCommand command = commandManager.getCommand(commandName);
            command.execute(args, txtConsola);
        } else {
            appendToConsole("Error: Entrada vacia.");
        }
    }
    
    private String getLastCommand(){
        String[] lines = txtConsola.getText().split("\n");
        return lines[lines.length-1].trim();
    }
    
    private void appendToConsole(String text){
        txtConsola.append("\n" + text);
    }
    
    private void initializerMatrix(JPanel pnl,JButton[][] buttonMatrix){
        pnl.setLayout(new GridLayout(5,10,1,1));
        buttonMatrix = new JButton[5][10];
        
        for(int i = 0; i < 5; i++){
            for (int j = 0; j < 10; j++){
                JButton btn = new JButton();
                btn.setOpaque(false);
                btn.setContentAreaFilled(false);
                btn.setBorder(BorderFactory.createLineBorder(Color.BLACK,1));
                btn.setFocusPainted(false);
                btn.setName("button" + i + "_" + j);
                buttonMatrix[i][j] = btn;
                pnl.add(btn);
            }
        }
        // Actualizar la vista del panel
        pnl.revalidate();
        pnl.repaint();
        
        // Asegurarse de que la referencia global sea asignada
        this.dmgMatrix=buttonMatrix;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        pnlRanking = new javax.swing.JPanel();
        pnlDatosContrincante = new javax.swing.JPanel();
        pnlDatosPropios = new javax.swing.JPanel();
        pnlAtaqueRecibido = new javax.swing.JPanel();
        pnlAtaqueLanzado = new javax.swing.JPanel();
        pnlCartas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCard1 = new javax.swing.JLabel();
        lblCard2 = new javax.swing.JLabel();
        lblCard3 = new javax.swing.JLabel();
        lblCard4 = new javax.swing.JLabel();
        lblNombreHabilidad1 = new javax.swing.JLabel();
        lblVidaCarta1 = new javax.swing.JLabel();
        lblVidaCarta2 = new javax.swing.JLabel();
        lblVidaCarta3 = new javax.swing.JLabel();
        lblVidaCarta4 = new javax.swing.JLabel();
        lblNombreCartaSeleccionada1 = new javax.swing.JLabel();
        lblNombreHabilidad2 = new javax.swing.JLabel();
        lblNombreHabilidad3 = new javax.swing.JLabel();
        lblNombreHabilidad4 = new javax.swing.JLabel();
        lblNombreHabilidad5 = new javax.swing.JLabel();
        pnlMostrarDmgHabilidades = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane1.setViewportView(txtConsola);

        pnlRanking.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout pnlRankingLayout = new javax.swing.GroupLayout(pnlRanking);
        pnlRanking.setLayout(pnlRankingLayout);
        pnlRankingLayout.setHorizontalGroup(
            pnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        pnlRankingLayout.setVerticalGroup(
            pnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        pnlDatosContrincante.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlDatosContrincanteLayout = new javax.swing.GroupLayout(pnlDatosContrincante);
        pnlDatosContrincante.setLayout(pnlDatosContrincanteLayout);
        pnlDatosContrincanteLayout.setHorizontalGroup(
            pnlDatosContrincanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        pnlDatosContrincanteLayout.setVerticalGroup(
            pnlDatosContrincanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        pnlDatosPropios.setBackground(new java.awt.Color(255, 153, 255));

        javax.swing.GroupLayout pnlDatosPropiosLayout = new javax.swing.GroupLayout(pnlDatosPropios);
        pnlDatosPropios.setLayout(pnlDatosPropiosLayout);
        pnlDatosPropiosLayout.setHorizontalGroup(
            pnlDatosPropiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        pnlDatosPropiosLayout.setVerticalGroup(
            pnlDatosPropiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pnlAtaqueRecibido.setBackground(new java.awt.Color(255, 51, 102));

        javax.swing.GroupLayout pnlAtaqueRecibidoLayout = new javax.swing.GroupLayout(pnlAtaqueRecibido);
        pnlAtaqueRecibido.setLayout(pnlAtaqueRecibidoLayout);
        pnlAtaqueRecibidoLayout.setHorizontalGroup(
            pnlAtaqueRecibidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlAtaqueRecibidoLayout.setVerticalGroup(
            pnlAtaqueRecibidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlAtaqueLanzado.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout pnlAtaqueLanzadoLayout = new javax.swing.GroupLayout(pnlAtaqueLanzado);
        pnlAtaqueLanzado.setLayout(pnlAtaqueLanzadoLayout);
        pnlAtaqueLanzadoLayout.setHorizontalGroup(
            pnlAtaqueLanzadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        pnlAtaqueLanzadoLayout.setVerticalGroup(
            pnlAtaqueLanzadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCartas.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("MY CARDS");

        lblCard1.setOpaque(true);

        lblCard2.setOpaque(true);

        lblCard3.setOpaque(true);

        lblCard4.setOpaque(true);

        lblNombreHabilidad1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblNombreHabilidad1.setText("cardName");

        lblVidaCarta1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblVidaCarta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVidaCarta1.setText("vida");

        lblVidaCarta2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblVidaCarta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVidaCarta2.setText("vida");

        lblVidaCarta3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblVidaCarta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVidaCarta3.setText("vida");

        lblVidaCarta4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblVidaCarta4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVidaCarta4.setText("vida");

        lblNombreCartaSeleccionada1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblNombreCartaSeleccionada1.setText("cardName");

        lblNombreHabilidad2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblNombreHabilidad2.setText("cardName");

        lblNombreHabilidad3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblNombreHabilidad3.setText("cardName");

        lblNombreHabilidad4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblNombreHabilidad4.setText("cardName");

        lblNombreHabilidad5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblNombreHabilidad5.setText("cardName");

        javax.swing.GroupLayout pnlMostrarDmgHabilidadesLayout = new javax.swing.GroupLayout(pnlMostrarDmgHabilidades);
        pnlMostrarDmgHabilidades.setLayout(pnlMostrarDmgHabilidadesLayout);
        pnlMostrarDmgHabilidadesLayout.setHorizontalGroup(
            pnlMostrarDmgHabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        pnlMostrarDmgHabilidadesLayout.setVerticalGroup(
            pnlMostrarDmgHabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCartasLayout = new javax.swing.GroupLayout(pnlCartas);
        pnlCartas.setLayout(pnlCartasLayout);
        pnlCartasLayout.setHorizontalGroup(
            pnlCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartasLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(lblCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(pnlCartasLayout.createSequentialGroup()
                .addGroup(pnlCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCartasLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblVidaCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lblVidaCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lblVidaCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(lblVidaCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCartasLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreCartaSeleccionada1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCartasLayout.createSequentialGroup()
                                .addGroup(pnlCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreHabilidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreHabilidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreHabilidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreHabilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreHabilidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlMostrarDmgHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCartasLayout.setVerticalGroup(
            pnlCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCard1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblCard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCard3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(pnlCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVidaCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVidaCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVidaCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVidaCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCartasLayout.createSequentialGroup()
                        .addComponent(lblNombreCartaSeleccionada1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(pnlCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCartasLayout.createSequentialGroup()
                                .addComponent(lblNombreHabilidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombreHabilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addComponent(lblNombreHabilidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(lblNombreHabilidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreHabilidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlMostrarDmgHabilidades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlDatosContrincante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlDatosPropios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlAtaqueLanzado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlAtaqueRecibido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(pnlCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(pnlRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlDatosPropios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlAtaqueRecibido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDatosContrincante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlAtaqueLanzado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pnlCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCard1;
    private javax.swing.JLabel lblCard2;
    private javax.swing.JLabel lblCard3;
    private javax.swing.JLabel lblCard4;
    private javax.swing.JLabel lblNombreCartaSeleccionada1;
    private javax.swing.JLabel lblNombreHabilidad1;
    private javax.swing.JLabel lblNombreHabilidad2;
    private javax.swing.JLabel lblNombreHabilidad3;
    private javax.swing.JLabel lblNombreHabilidad4;
    private javax.swing.JLabel lblNombreHabilidad5;
    private javax.swing.JLabel lblVidaCarta1;
    private javax.swing.JLabel lblVidaCarta2;
    private javax.swing.JLabel lblVidaCarta3;
    private javax.swing.JLabel lblVidaCarta4;
    private javax.swing.JPanel pnlAtaqueLanzado;
    private javax.swing.JPanel pnlAtaqueRecibido;
    private javax.swing.JPanel pnlCartas;
    private javax.swing.JPanel pnlDatosContrincante;
    private javax.swing.JPanel pnlDatosPropios;
    private javax.swing.JPanel pnlMostrarDmgHabilidades;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlRanking;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables
}
